### ISSUE TITLE
Handshake error?

### ISSUE THREAD

**Issue by joeytakeda** [internetshakespeare/ise2-import#2]
I tried to run using

```
ant -lib lib 
```

and got this error:

```
get-tei-xsl:
      [get] Getting: https://sourceforge.net/projects/tei/files/Stylesheets/tei-xsl-7.43.0.zip/download
      [get] To: /Users/joeytakeda/ise/ise3/ise2-import/lib/tei-xsl-7.43.0.zip
      [get] Error getting https://sourceforge.net/projects/tei/files/Stylesheets/tei-xsl-7.43.0.zip/download to /Users/joeytakeda/ise/ise3/ise2-import/lib/tei-xsl-7.43.0.zip

BUILD FAILED
/Users/joeytakeda/ise/ise3/ise2-import/build.xml:150: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:728)
	at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:641)
	at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:631)

```

**Comment by telic** [comment]
Do you have your ANT_OPTS variable still set to use the trustStore.jks from the old script? The new script won't work with it.

**Comment by joeytakeda** [comment]
Ah, that was it! Thanks!
